name: my-workflow
on: [workflow_dispatch, push]
jobs:
  frist-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo "Hello World..!"
      - name: github checkout
        uses:  actions/checkout@v7
  second-job:
      needs: frist-job
      runs-on: ubuntu-latest
      steps: 
      - name: test-step
        run: echo "this is test step"
      - name: test-code
        uses:  actions/checkout@v7