name: my-workflow
on: workflow_dispatch
jobs:
  frist-job:
    runs-on: ubuntu-latest
    steps: 
      - name: frist-step
        run: echo "Hello World..!"
      - name: github checkout
        uses:  actions/checkout@v7